// Generated by CoffeeScript 1.12.5
(function() {
  var body, k, ref, v;

  window.getName = function(name) {
    if (name == null) {
      name = "Aman";
    }
    return "sfjashjf " + name + " asdfhjasdf";
  };

  window.onload = function(e) {
    console.log(111);
    return false;
  };

  ref = [1, 2, 3, 4];
  for (k in ref) {
    v = ref[k];
    console.log(k, v);
  }

  body = document;

  body.addEventListener("click", function(e) {
    alert();
    return false;
  });

}).call(this);
